### ISSUE TITLE
Is there any working Node example?

### ISSUE THREAD

**Issue by kjur** [GlobalSign/PKI.js#63]
Hi. Is there any working Node example?

README example seems not to work properly.

https://github.com/GlobalSign/PKI.js
This part works fine but proceeding codes can't be merged by X509 schema reference error.

``` JavaScript
var asn1 = pkijs.org.pkijs.fromBER(certBuffer);
var cert;
try {
    cert = new pkijs.org.pkijs.simpl.CERT({ schema: asn1.result });
} catch(ex) {
    return;
}
```

Thanks.

**Comment by YuryStrozhevsky** [comment]
Here is a cut from my working project:
```javascript
var common = require("asn1js/org/pkijs/common");
var _asn1js = require("asn1js");
var _pkijs = require("pkijs");
var _x509schema = require("pkijs/org/pkijs/x509_schema");
var _x509simpl = require("pkijs/org/pkijs/x509_simpl");
var _ocsp_tsp_schema = require("pkijs/org/pkijs/ocsp_tsp_schema");
var _ocsp_tsp_simpl = require("pkijs/org/pkijs/ocsp_tsp_simpl");
var _cms_schema = require("pkijs/org/pkijs/cms_schema");
var _cms_simpl = require("pkijs/org/pkijs/cms_simpl");
var _cades_schema = require("pkijs/org/pkijs/cades_schema");
var _cades_simpl = require("pkijs/org/pkijs/cades_simpl_node");

// #region Merging function/object declarations for ASN1js and PKIjs 
var asn1js = merge(true, _asn1js, common);

var x509schema = merge(true, _x509schema, asn1js);

var pkijs_1 = merge(true, _pkijs, asn1js);
var pkijs_2 = merge(true, pkijs_1, x509schema);
var pkijs_3 = merge(true, pkijs_2, _x509simpl);

var ocsp_tsp_schema = merge(true, _ocsp_tsp_schema, asn1js);
ocsp_tsp_schema = merge(true, ocsp_tsp_schema, _x509schema);

var cades_schema = merge(true, _cades_schema, asn1js);
cades_schema = merge(true, cades_schema, _x509schema);
cades_schema = merge(true, _cms_schema, _x509schema);

var pkijs_4 = merge(true, pkijs_3, _ocsp_tsp_schema);

var ocsp_tsp_simpl = merge(true, _ocsp_tsp_simpl, _x509simpl);
var ocsp_tsp_simpl_1 = merge(true, ocsp_tsp_simpl, asn1js);

var cades_simpl = merge(true, _cades_simpl, _x509simpl);
cades_simpl = merge(true, cades_simpl, asn1js);

var cms_simpl = merge(true, _cms_simpl, _x509simpl);
cms_simpl = merge(true, cms_simpl, asn1js);

var pkijs = merge(true, pkijs_4, _ocsp_tsp_simpl);
pkijs = merge(true, pkijs, cms_simpl);
pkijs = merge(true, pkijs, cades_simpl);
// #endregion 
// #endregion 
```
You can use it if you wish.

**Comment by kjur** [comment]
Thank you for reply however I got this error in your example:

module.js:327
    throw err;
    ^

Error: Cannot find module 'pkijs/org/pkijs/cades_schema'

**Comment by YuryStrozhevsky** [comment]
Sure, it is not published yet :) Just remove all references to "cades_..." files.

**Comment by kjur** [comment]
I've removed cades references then still I got x509 schema reference error:

```JavaScript
#!/usr/bin/env node

var merge = require("node.extend");
var common = require("asn1js/org/pkijs/common");
var _asn1js = require("asn1js");
var _pkijs = require("pkijs");
var _x509schema = require("pkijs/org/pkijs/x509_schema");
var _x509simpl = require("pkijs/org/pkijs/x509_simpl");
var _ocsp_tsp_schema = require("pkijs/org/pkijs/ocsp_tsp_schema");
var _ocsp_tsp_simpl = require("pkijs/org/pkijs/ocsp_tsp_simpl");
var _cms_schema = require("pkijs/org/pkijs/cms_schema");
var _cms_simpl = require("pkijs/org/pkijs/cms_simpl");
//var _cades_schema = require("pkijs/org/pkijs/cades_schema");
//var _cades_simpl = require("pkijs/org/pkijs/cades_simpl_node");

// #region Merging function/object declarations for ASN1js and PKIjs 
var asn1js = merge(true, _asn1js, common);

var x509schema = merge(true, _x509schema, asn1js);

var pkijs_1 = merge(true, _pkijs, asn1js);
var pkijs_2 = merge(true, pkijs_1, x509schema);
var pkijs_3 = merge(true, pkijs_2, _x509simpl);

var ocsp_tsp_schema = merge(true, _ocsp_tsp_schema, asn1js);
ocsp_tsp_schema = merge(true, ocsp_tsp_schema, _x509schema);

//var cades_schema = merge(true, _cades_schema, asn1js);
//cades_schema = merge(true, cades_schema, _x509schema);
//cades_schema = merge(true, _cms_schema, _x509schema);

var pkijs_4 = merge(true, pkijs_3, _ocsp_tsp_schema);

var ocsp_tsp_simpl = merge(true, _ocsp_tsp_simpl, _x509simpl);
var ocsp_tsp_simpl_1 = merge(true, ocsp_tsp_simpl, asn1js);

//var cades_simpl = merge(true, _cades_simpl, _x509simpl);
//cades_simpl = merge(true, cades_simpl, asn1js);

var cms_simpl = merge(true, _cms_simpl, _x509simpl);
cms_simpl = merge(true, cms_simpl, asn1js);

var pkijs = merge(true, pkijs_4, _ocsp_tsp_simpl);
pkijs = merge(true, pkijs, cms_simpl);
//pkijs = merge(true, pkijs, cades_simpl);

//=================================
var buffer = new ArrayBuffer();

var asn1 = pkijs.org.pkijs.fromBER(buffer);
var cert_simpl = new pkijs.org.pkijs.simpl.CERT({ schema: asn1.result });

// =======
cert_simpl.serialNumber = new pkijs.org.pkijs.asn1.INTEGER({ value: 1 });
cert_simpl.issuer.types_and_values.push(new pkijs.org.pkijs.simpl.ATTR_TYPE_AND_VALUE({
    type: "2.5.4.6", // Country name
    value: new pkijs.org.pkijs.asn1.PRINTABLESTRING({ value: "RU" })
}));
cert_simpl.issuer.types_and_values.push(new pkijs.org.pkijs.simpl.ATTR_TYPE_AND_VALUE({
    type: "2.5.4.3", // Common name
    value: new pkijs.org.pkijs.asn1.PRINTABLESTRING({ value: "Test" })
}));
cert_simpl.subject.types_and_values.push(new pkijs.org.pkijs.simpl.ATTR_TYPE_AND_VALUE({
    type: "2.5.4.6", // Country name
    value: new pkijs.org.pkijs.asn1.PRINTABLESTRING({ value: "RU" })
}));
cert_simpl.subject.types_and_values.push(new pkijs.org.pkijs.simpl.ATTR_TYPE_AND_VALUE({
    type: "2.5.4.3", // Common name
    value: new pkijs.org.pkijs.asn1.PRINTABLESTRING({ value: "Test" })
}));

cert_simpl.notBefore.value = new Date(2013, 01, 01);
cert_simpl.notAfter.value = new Date(2016, 01, 01);

cert_simpl.extensions = new Array();

// #region "BasicConstraints" extension
var basic_constr = new pkijs.org.pkijs.simpl.x509.BasicConstraints({
    cA: true,
    pathLenConstraint: 3
});

cert_simpl.extensions.push(new pkijs.org.pkijs.simpl.EXTENSION({
    extnID: "2.5.29.19",
    critical: false,
    extnValue: basic_constr.toSchema().toBER(false),
    parsedValue: basic_constr // Parsed value for well-known extensions
}));
// #endregion 

// #region "KeyUsage" extension 
var bit_array = new ArrayBuffer(1);
var bit_view = new Uint8Array(bit_array);

bit_view[0] = bit_view[0] | 0x02; // Key usage "cRLSign" flag
bit_view[0] = bit_view[0] | 0x04; // Key usage "keyCertSign" flag

var key_usage = new pkijs.org.pkijs.asn1.BITSTRING({ value_hex: bit_array });

cert_simpl.extensions.push(new pkijs.org.pkijs.simpl.EXTENSION({
    extnID: "2.5.29.15",
    critical: false,
    extnValue: key_usage.toBER(false),
    parsedValue: key_usage // Parsed value for well-known extensions
}));
```

This raises following error:

```
/opt/local/lib/node_modules/pkijs/org/pkijs/x509_simpl.js:3912
            throw new Error("Object's schema was not verified against input data for CERT");
            ^

Error: Object's schema was not verified against input data for CERT
    at in_window.org.pkijs.simpl.CERT.fromSchema (/opt/local/lib/node_modules/pkijs/org/pkijs/x509_simpl.js:3912:19)
    at new in_window.org.pkijs.simpl.CERT (/opt/local/lib/node_modules/pkijs/org/pkijs/x509_simpl.js:3854:65)
    at Object.<anonymous> (/Users/user1/Dropbox/workuniq/pkijs-sample/sample_node/a2:51:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

**Comment by YuryStrozhevsky** [comment]
No, you do not need these lines at the beggining:
```javascript
var buffer = new ArrayBuffer();

var asn1 = pkijs.org.pkijs.fromBER(buffer);
var cert_simpl = new pkijs.org.pkijs.simpl.CERT({ schema: asn1.result });
```
These lines are for case when you need to parse existing certificate. But as I can see you would like to create a new one. So, for this case you only need one line:
```javascript
var cert_simpl = new pkijs.org.pkijs.simpl.CERT();
```
And that is all. Please refer to [this example, create_CERT function](https://github.com/GlobalSign/PKI.js/blob/master/examples/Certificate%20complex%20example/X509_cert_complex_example.html).
