### ISSUE TITLE
How to view cert data in node.js

### ISSUE THREAD

**Issue by coolaj86** [GlobalSign/PKI.js#66]
I did my best to piece together the examples to get certificate info:

```javascript
'use strict';

var merge = require("node.extend");

var common = require("asn1js/org/pkijs/common");
var _asn1js = require("asn1js");
var _pkijs = require("pkijs");
var _x509schema = require("pkijs/org/pkijs/x509_schema");

// #region Merging function/object declarations for ASN1js and PKIjs
var asn1js = merge(true, _asn1js, common);

var x509schema = merge(true, _x509schema, asn1js);

var pkijs_1 = merge(true, _pkijs, asn1js);
var pkijs = merge(true, pkijs_1, x509schema);

var pem = require('fs').readFileSync('./example.cert.pem', 'ascii');
var asn1 = pkijs.org.pkijs.fromBER(pem);
var cert_simpl = new pkijs.org.pkijs.simpl.CERT({ schema: asn1.result });

console.log(cert_simpl);
```

But then I got an error about object schema:
```
/home/aj/letsencrypt-express.new/node_modules/pkijs/org/pkijs/x509_simpl.js:3912
            throw new Error("Object's schema was not verified against input data for CERT");
            ^

Error: Object's schema was not verified against input data for CERT
    at in_window.org.pkijs.simpl.CERT.fromSchema (/home/aj/letsencrypt-express.new/node_modules/pkijs/org/pkijs/x509_simpl.js:3912:19)
    at new in_window.org.pkijs.simpl.CERT (/home/aj/letsencrypt-express.new/node_modules/pkijs/org/pkijs/x509_simpl.js:3854:65)
    at Object.<anonymous> (/home/aj/letsencrypt-express.new/cert-info.js:20:18)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
```

Where did I go wrong?

This is the cert in question:

```
-----BEGIN CERTIFICATE-----
MIIE+DCCA+CgAwIBAgISA2ZPXaADSdfNg48RtgfQGS9IMA0GCSqGSIb3DQEBCwUA
MEoxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MSMwIQYDVQQD
ExpMZXQncyBFbmNyeXB0IEF1dGhvcml0eSBYMzAeFw0xNjA1MTMyMzM4MDBaFw0x
NjA4MTEyMzM4MDBaMBUxEzARBgNVBAMTCm9hdXRoMy5vcmcwggEiMA0GCSqGSIb3
DQEBAQUAA4IBDwAwggEKAoIBAQDpm3D2yi79yHcnyv7JdNs7fVUO7Kcxq52qruyI
svMfq1gd7W1m6L7OPlRNvsae3/Yuca2Ip+JPXcCphhhb63/ChUSp5efbo0JYg6EZ
L/5TaV8HyovONEfleuYWSaBZ6RaRAZYBDclIJ13wgsYbJPYE5lSV2ufdAr9OIYrk
myo5+WPVxZpDS7+fBY+fUnxJ8BOs1R7q/xfnDaipTc0ZsNQlQwOIkvQOy0D4otwx
61MsrjPoQf686fex/HPwWi5sfKmH3YyB2ClnaIFv2wFs9fxCyb2htBn79Y98l4rV
Ved21MllyReMKsk9J2Sx+3ONHr8Qpo1chHEu56MbbMXgqsmlAgMBAAGjggILMIIC
BzAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMC
MAwGA1UdEwEB/wQCMAAwHQYDVR0OBBYEFK8RJxCWMQgo8OHf2ILIIqatdHZkMB8G
A1UdIwQYMBaAFKhKamMEfd265tE5t6ZFZe/zqOyhMHAGCCsGAQUFBwEBBGQwYjAv
BggrBgEFBQcwAYYjaHR0cDovL29jc3AuaW50LXgzLmxldHNlbmNyeXB0Lm9yZy8w
LwYIKwYBBQUHMAKGI2h0dHA6Ly9jZXJ0LmludC14My5sZXRzZW5jcnlwdC5vcmcv
MBUGA1UdEQQOMAyCCm9hdXRoMy5vcmcwgf4GA1UdIASB9jCB8zAIBgZngQwBAgEw
geYGCysGAQQBgt8TAQEBMIHWMCYGCCsGAQUFBwIBFhpodHRwOi8vY3BzLmxldHNl
bmNyeXB0Lm9yZzCBqwYIKwYBBQUHAgIwgZ4MgZtUaGlzIENlcnRpZmljYXRlIG1h
eSBvbmx5IGJlIHJlbGllZCB1cG9uIGJ5IFJlbHlpbmcgUGFydGllcyBhbmQgb25s
eSBpbiBhY2NvcmRhbmNlIHdpdGggdGhlIENlcnRpZmljYXRlIFBvbGljeSBmb3Vu
ZCBhdCBodHRwczovL2xldHNlbmNyeXB0Lm9yZy9yZXBvc2l0b3J5LzANBgkqhkiG
9w0BAQsFAAOCAQEAfD/fMRxCZqMeQKFjyM6LIt9k84aHDdkem0ZmMUlYDuiz9iI5
ZeL20gYopLQ+vcKe/1vHnODnEcEhBjzNM/aVXQVHi/xokDf4Loks6fP2cslGMMFy
Kqgz3JaEcIs3ENjBBIU0xGQGuN67eZK8yhfrQxQuZOIx9J+IyP1jyFQSGA2c9wQD
KRPUCef3EZhBaL1DXlMB8fqQOq0EP0IF2Qsp5MlkYaM9N3U/xbjku74lGBkJnS5n
f2GE45RdY8KlIkJtkNhbGNX+nYHgbATUoO5uTKlcBslC+uwVqDDF3gbpdvAKE4a8
eh6155o4h8lnhZD4Okr0KvdZT17jH+j4cbkRXw==
-----END CERTIFICATE-----
```

**Comment by YuryStrozhevsky** [comment]
PKIjs works *only* with raw data. So, you need to do something simular with [this example](https://github.com/GlobalSign/PKI.js/blob/master/examples/certificate-decode-example.html#L137).

**Comment by coolaj86** [comment]
The example didn't work:

```
git clone https://github.com/GlobalSign/PKI.js.git
pushd PKI.js/
pushd examples
ln -s ../org ./

npm install -g server-https
serve-https
```

When I click `Decode` it gives me `TypeError: org.pkijs.fromBER is not a function`

Also, I updated my code to use an ArrayBuffer, just as the example does, but it still throws the same error:

```
'use strict';

var merge = require("node.extend");

var common = require("asn1js/org/pkijs/common");
var _asn1js = require("asn1js");
var _pkijs = require("pkijs");
var _x509schema = require("pkijs/org/pkijs/x509_schema");

// #region Merging function/object declarations for ASN1js and PKIjs
var asn1js = merge(true, _asn1js, common);

var x509schema = merge(true, _x509schema, asn1js);

var pkijs_1 = merge(true, _pkijs, asn1js);
var pkijs = merge(true, pkijs_1, x509schema);

var pem = require('fs').readFileSync('./example.cert.pem', 'ascii');
var b64 = pem.replace(/(-----(BEGIN|END) CERTIFICATE-----|[\n\r])/g, '');
var ber = Buffer.from(b64, 'base64').buffer;
var asn1 = pkijs.org.pkijs.fromBER(ber);
var cert_simpl = new pkijs.org.pkijs.simpl.CERT({ schema: asn1.result }); // throws error

console.log(cert_simpl);
```

**Comment by YuryStrozhevsky** [comment]
Can you parse this certificate using [this example](https://pkijs.org/examples/X509_cert_complex_example.html)? Note: the example also decodes only raw (BASE-64 decoded) data.

**Comment by YuryStrozhevsky** [comment]
If yes then try to find a mistakes in your Node program.

**Comment by coolaj86** [comment]
Apparently node's Buffer.buffer returns the allocated ArrayBuffer, not the used portion of the ArrayBuffer.

This works:

```
'use strict';

var merge = require("node.extend");

var common = require("asn1js/org/pkijs/common");
var _asn1js = require("asn1js");
var _pkijs = require("pkijs");
var _x509schema = require("pkijs/org/pkijs/x509_schema");

// #region Merging function/object declarations for ASN1js and PKIjs
var asn1js = merge(true, _asn1js, common);

var x509schema = merge(true, _x509schema, asn1js);

var pkijs_1 = merge(true, _pkijs, asn1js);
var pkijs = merge(true, pkijs_1, x509schema);

var pem = require('fs').readFileSync('./example.cert.pem', 'ascii');
var b64 = pem.replace(/(-----(BEGIN|END) CERTIFICATE-----|[\n\r])/g, '');
var buf = Buffer(b64, 'base64');
var ab = new Uint8Array(buf).buffer;          // WORKS
//var ab = buf.buffer                         // Doesn't work
console.log(ab);
var asn1 = pkijs.org.pkijs.fromBER(ab);
var cert_simpl = new pkijs.org.pkijs.simpl.CERT({ schema: asn1.result });

console.log(cert_simpl);
```


Do you have a place where node examples can go?

**Comment by YuryStrozhevsky** [comment]
I have local test plant for testing PKIjs on Node.

BTW: as soon you a making a new project using PKIjs please consider to design it using [new upcoming version of PKIjs](https://github.com/PeculiarVentures/pkijs-es6) [(and ASN1js as well)](https://github.com/PeculiarVentures/asn1js-es6). These are ES6 version of existing libraries and v1 versions would be replaced by them very soon. But please consider that we did not finished testing for these new libs and some parts could be still buggy.

**Comment by rmhrisk** [comment]
We would be happy to take a pull request for a sample for node if you have one you think is good.

As Yury says we are finishing up a ES6 rewrite of PKIjs and this may be a better solution for you, the ES5 version will continue to be available though.
